import React from "react";
import Header from "../components/layouts/header";
import Footer from "../components/layouts/footer";
import { FaHome } from "react-icons/fa";
import Head from "next/head";
import Input from "../components/input";

const Contact = () => {
    return (
        <div>
            <Head>
                <title>Contact</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin="true"
                />
            </Head>
            <Header />
            <div
                className="banner pt-10 pb-10"
                style={{
                    backgroundImage: "url(/img/background.png)",
                }}
            >
                <div className="container mx-auto">
                    <div className="flex items-center">
                        <div className="w-full">
                            <div className="title-area-data">
                                <h2 className="font-fredoka font-bold text-6xl">Contact</h2>
                                <p>A magical combination that sent aromas to the taste buds</p>
                            </div>
                            <ol className="breadcrumb bg-pink font-fredoka">
                                <li className="breadcrumb-item">
                                    <a href="" className="flex items-center">
                                        <FaHome /> <span className="ml-3">Home</span>
                                    </a>
                                </li>
                                <li className="breadcrumb-item active" aria-current="page">
                                    Contact
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <section className="gap font-fredoka">
                <div className="container mx-auto">
                    <div className="flex items-center  max-lg:block">
                        <div className="w-1/2 max-lg:w-full">
                            <div className="parties-events-text">
                                <div className="get-in-touch">
                                    <h2 className="text-6xl font-bold">Have Question?</h2>
                                    <p className="text-[#555]">For all enquires, please contact us and one of our delightful team will be be happy to help.</p>
                                </div>
                            </div>
                            <form role="form" id="contact-form" method="post" className="add-review leave-comment mt-4" />
                            <div className="w-full my-5">
                                <Input />
                            </div>
                            <div className="w-full my-5">
                                <Input />
                            </div> <div className="w-full my-5">
                                <Input />
                            </div>
                            <button className="button bg-pink mt-5" type="submit" value="submit" >
                                <span>send Message</span>
                            </button>
                            <form />
                        </div>
                        <div className="w-1/2 max-lg:w-full">
                            <div className="mapouter ml-10 max-lg:ml-0">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26358986.39359313!2d-113.7115859681645!3d36.24800244048599!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54eab584e432360b%3A0x1c3bb99243deb742!2sUnited%20States!5e0!3m2!1sen!2s!4v1676996184286!5m2!1sen!2s" width="100%" height="450" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
            </section >
            <Footer />
        </div >
    )
}

export default Contact