import React from "react";
import Head from "next/head";
import Carousel from "../components/carousel";
import Menu from "../components/menu";
import Banner from "../components/banner";
import Brand from "../components/brand";
import New from "../components/new";
import App from "../components/app";
import Feature from "../components/feature";
import Reserve from "../components/reserve";
const Index = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
      </Head>
      <Carousel />
      <Menu />
      <Feature />
      <Banner />
      <Reserve />
      <App />
      <New />
      <Brand />
    </div>
  );
};
export default Index;
