import React from "react";
import { FaHome } from "react-icons/fa";
import Head from "next/head";
import { useFormik } from "formik";
import Input from "../components/input";
import { loginSchema } from "../components/schema/login";
const Login = () => {
    const onSubmit = async (values, actions) => {
        await new Promise((resolve) => setTimeout(resolve, 4000));
        actions.resetForm();
    };

    const { values, errors, touched, handleSubmit, handleChange, handleBlur } = useFormik({
        initialValues: {
            email: "",
            password: "",
            rememberMe: "",
            fullName: ""
        },
        onSubmit,
        validationSchema: loginSchema,
    });

    const loginInputs = [
        {
            id: 1,
            name: "email",
            type: "email",
            placeholder: "Your E-Mail",
            values: values.email,
            errorMessage: errors.email,
            touched: touched.email
        },
        {
            id: 2,
            name: "password",
            type: "password",
            placeholder: "Your Password",
            values: values.password,
            errorMessage: errors.password,
            touched: touched.password
        },
        {
            id: 3,
            name: "rememberMe",
            type: "checkbox",
            placeholder: "",
            values: values.rememberMe,
            errorMessage: errors.rememberMe,
            touched: touched.rememberMe
        }
    ];

    const registerInputs = [
        {
            id: 1,
            name: "fullName",
            type: "text",
            placeholder: "Your Full Name",
            values: values.fullName,
            errorMessage: errors.fullName,
            touched: touched.fullName
        },
        {
            id: 2,
            name: "email",
            type: "email",
            placeholder: "Your E-Mail",
            values: values.email,
            errorMessage: errors.email,
            touched: touched.email
        },
        {
            id: 3,
            name: "password",
            type: "password",
            placeholder: "Your Password",
            values: values.password,
            errorMessage: errors.password,
            touched: touched.password
        }
    ];
    return (
        <div>
            <Head>
                <title>Login</title>
                <meta name="description" csontent="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin="true"
                />
            </Head>
            <div
                className="banner pt-10 pb-10"
                style={{
                    backgroundImage: "url(/img/background.png)",
                }}
            >
                <div className="container mx-auto">
                    <div className="flex items-center">
                        <div className="w-full">
                            <div className="title-area-data">
                                <h2 className="font-fredoka font-bold text-6xl">Login</h2>
                                <p>A magical combination that sent aromas to the taste buds</p>
                            </div>
                            <ol className="breadcrumb bg-pink font-fredoka">
                                <li className="breadcrumb-item">
                                    <a href="" className="flex items-center">
                                        <FaHome /> <span className="ml-3">Home</span>
                                    </a>
                                </li>
                                <li className="breadcrumb-item active" aria-current="page">
                                    Login
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <section className="gap font-fredoka font-bold">
                <div className="container mx-auto">
                    <div className="flex flex-wrap max-lg:block">
                        <div className="w-1/2 max-lg:w-full">
                            <div className="box login mr-3 max-lg:mr-0">
                                <h3>Log In Your Account</h3>
                                <form onSubmit={handleSubmit} >
                                    {loginInputs.map((input) => (
                                        input.id != 3 &&
                                        <Input key={input.id} {...input}
                                            onChange={handleChange}
                                            onBlur={handleBlur} />
                                    ))}
                                    <div className="remember flex justify-between items-center">
                                        <div className="first flex justify-between items-center">
                                            {loginInputs.map((input) => (
                                                input.id == 3 &&
                                                <Input key={input.id} {...input}
                                                    onChange={handleChange}
                                                    onBlur={handleBlur} />
                                            ))}
                                            <label for="checkbox">Remember me</label>
                                        </div>
                                        <div className="second">
                                            <a href="javascript:void(0)" className="text-pink text-sm">Forget a Password?</a>
                                        </div>
                                    </div>
                                    <button type="submit" className="button bg-pink mt-5">Login</button>
                                </form>
                            </div>
                        </div>
                        <div className="w-1/2 max-lg:w-full max-lg:mt-5">
                            <div className="box register ml-2 max-lg:ml-0">
                                <div className="parallax" style={{
                                    backgroundImage: "url( /img/patron.jpg)",
                                }}></div>
                                <h3>Log In Your Account</h3>
                                <form onSubmit={handleSubmit}>
                                    {registerInputs.map((input) => (
                                        <Input key={input.id} {...input}
                                            onChange={handleChange}
                                            onBlur={handleBlur} />
                                    ))}
                                    <p className="text-white text-sm">Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our privacy policy.</p>
                                    <button type="submit" className="button mt-5">Register</button>
                                </form >
                            </div>
                        </div>
                    </div>
                </div>
            </section>

        </div>)
}

export default Login