import React from "react";

import Head from "next/head";
import Image from "next/image";
import { FaHome } from "react-icons/fa";
const MenuItem = () => {
  return (
    <div className="flex max-sm:block items-center discover-menu">
      <div className="w-1/2 max-sm:w-full mr-10">
        <div className="discover-img">
          <Image
            src="/img/discover-7.png"
            width={610}
            height={520}
            alt="discover"
          ></Image>
        </div>
      </div>
      <div className="w-1/2 max-sm:w-full mr-10">
        <div className="discover z-[2] relative">
          <h4 className="font-fredoka font-bold text-5xl">burger</h4>
          <ul>
            <li>
              <div>
                <h6 className="font-fredoka font-bold text-3xl">
                  Four Chease Garlic Bread
                </h6>
                <p>Toested french bread topped with romano</p>
              </div>
              <span className="font-fredoka font-bold text-pink">$9.00</span>
            </li>
            <li>
              <div>
                <h6 className="font-fredoka font-bold text-3xl">
                  Rastrami Roll
                </h6>
                <p>Spreadable cream cheese, blue cheese</p>
              </div>
              <span className="font-fredoka font-bold text-pink">$16.00</span>
            </li>
            <li>
              <div>
                <h6 className="font-fredoka font-bold text-3xl">
                  Caprese Salad Kabobs
                </h6>
                <p>Cherry-size fresh mozzarella cheese balls</p>
              </div>
              <span className="font-fredoka font-bold text-pink">$34.00</span>
            </li>
            <li>
              <div>
                <h6 className="font-fredoka font-bold text-3xl">
                  Peachy Jalepeno Guacomole
                </h6>
                <p>Ground cumin, avocados, peeled and cubed</p>
              </div>
              <span className="font-fredoka font-bold text-pink">$40.00</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};
const Menu = () => {
  return (
    <>
      <Head>
        <title>Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
</Head>
      <div
        className="banner pt-10 pb-10"
        style={{
          backgroundImage: "url(/img/background.png)",
        }}
      >
        <div className="container mx-auto">
          <div className="flex items-center">
            <div className="w-full">
              <div className="title-area-data">
                <h2 className="font-fredoka font-bold text-6xl">Table Menu</h2>
                <p>A magical combination that sent aromas to the taste buds</p>
              </div>
              <ol className="breadcrumb bg-pink font-fredoka">
                <li className="breadcrumb-item">
                  <a href="" className="flex items-center">
                    <FaHome /> <span className="ml-3">Home</span>
                  </a>
                </li>
                <li className="breadcrumb-item active" aria-current="page">
                  Menu
                </li>
              </ol>
            </div>
          </div>
        </div>
      </div>
      <section className="gap no-bottom">
        <div className="container mx-auto">
          <div className="w-full p-10">
            <MenuItem />
          </div>
          <div className="w-full p-10">
            <MenuItem />
          </div>
          <div className="w-full p-10">
            <MenuItem />
          </div>
          <div className="w-full p-10">
            <MenuItem />
          </div>
          <div className="w-full p-10">
            <MenuItem />
          </div>
        </div>
      </section>
    
    </>
  );
};
export default Menu;
