import React from "react";

import { FaHome, FaAngleLeft, FaAngleRight } from "react-icons/fa";
import Head from "next/head";
import Image from "next/image";
import Paginate from "../components/paginate";
const NewItem = () => {
  return (
    <div className="recent-news-two font-fredoka font-bold mb-10">
      <Image
        src="/img/recent-news-6.jpg"
        width={850}
        height={530}
        alt="recent-news-img"
        className="rounded-3xl"
      />
      <div className="recent-news mt-3">
        <div>
          <a href="newDetails">
            <span className="mb-3">29 December, 2023</span>
          </a>
          <a href="newDetails">
            <h2 className="text-4xl mb-3 hover:text-pink max-lg:text-2xl">
              Tender fried baby squid with a salt, pepper
            </h2>
          </a>
          <div className="flex items-center">
            <Image
              className="me-3"
              src="/img/man.jpg"
              width={55}
              height={55}
              alt="img"
            />
            <h6 className="ml-5">by Thomas Walimes</h6>
          </div>
        </div>
      </div>
    </div>
  );
};
const News = () => {
  return (
    <div>
      <Head>
        <title>News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
</Head>
      <div
        className="banner pt-10 pb-10"
        style={{
          backgroundImage: "url(/img/background.png)",
        }}
      >
        <div className="container mx-auto">
          <div className="flex items-center">
            <div className="w-full">
              <div className="title-area-data">
                <h2 className="font-fredoka font-bold text-6xl">News</h2>
                <p>A magical combination that sent aromas to the taste buds</p>
              </div>
              <ol className="breadcrumb bg-pink font-fredoka">
                <li className="breadcrumb-item">
                  <a href="" className="flex items-center">
                    <FaHome /> <span className="ml-3">Home</span>
                  </a>
                </li>
                <li className="breadcrumb-item active" aria-current="page">
                  News
                </li>
              </ol>
            </div>
          </div>
        </div>
      </div>
      <section className="gap our-blog font-fredoka font-bold">
        <div className="container mx-auto">
          <div className="flex flex-wrap justify-between max-xl:block">
            <div className="w-3/6 max-xl:w-full mr-2 max-md:mr-0">
              <NewItem />
              <NewItem />
              <NewItem />
              <Paginate />
            </div>
            <div className="w-2/6 max-xl:w-full max-md:ml-0 max-lg:mt-5 ">
              <div className="posts recent-posts">
                <h3 className="text-3xl">Recent Posts</h3>
                <ul>
                  <li>
                    <Image
                      className="me-3"
                      src="/img/recent-news-blog-1.jpg"
                      width={80}
                      height={80}
                      alt="img"
                    />
                    <div className="ml-4">
                      <a href="#" className="text-pink">
                        29 December, 2022
                      </a>
                      <h6>
                        <a href="#">Restaurant Located in on Bank Street</a>
                      </h6>
                    </div>
                  </li>
                  <li>
                    <Image
                      className="me-3"
                      src="/img/recent-news-blog-1.jpg"
                      width={80}
                      height={80}
                      alt="img"
                    />
                    <div className="ml-4">
                      <a href="#" className="text-pink">
                        29 December, 2022
                      </a>
                      <h6>
                        <a href="#">Restaurant Located in on Bank Street</a>
                      </h6>
                    </div>
                  </li>{" "}
                  <li>
                    <Image
                      className="me-3"
                      src="/img/recent-news-blog-1.jpg"
                      width={80}
                      height={80}
                      alt="img"
                    />
                    <div className="ml-4">
                      <a href="#" className="text-pink">
                        29 December, 2022
                      </a>
                      <h6>
                        <a href="#">Restaurant Located in on Bank Street</a>
                      </h6>
                    </div>
                  </li>
                </ul>
              </div>
              <div className="posts">
                <h3 className="text-3xl">Categories</h3>
                <ul className="categories">
                  <li className="pt-0">
                    <a href="#">
                      food<span>12</span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      Inspiration<span>13</span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      Lifestyle<span>19</span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      People<span>22</span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      Recipes <span>11</span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      World<span>08</span>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>
    
    </div>
  );
};
export default News;
