import Head from "next/head";
import React from "react";
import Footer from "../components/layouts/footer";
import Header from "../components/layouts/header";
import { FaHome, FaStar, FaCheck } from "react-icons/fa";
import Image from "next/image";
import Review from "../components/review";

const ProductDetails = () => {
  return (
    <>
      <Head>
        <title>Product Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
      </Head>
      <Header />
      <div
        className="banner pt-10 pb-10"
        style={{
          backgroundImage: "url(/img/background.png)",
        }}
      >
        <div className="container mx-auto">
          <div className="flex items-center">
            <div className="w-full">
              <div className="title-area-data">
                <h2 className="font-fredoka font-bold text-6xl">
                  Product Detail
                </h2>
                <p>A magical combination that sent aromas to the taste buds</p>
              </div>
              <ol className="breadcrumb bg-pink font-fredoka">
                <li className="breadcrumb-item">
                  <a href="" className="flex items-center">
                    <FaHome /> <span className="ml-3">Home</span>
                  </a>
                </li>
                <li className="breadcrumb-item text-white" aria-current="page">
                  Shop
                </li>
                <li className="breadcrumb-item active" aria-current="page">
                  Product Details
                </li>
              </ol>
            </div>
          </div>
        </div>
      </div>
      <section className="gap featured-dishes-product-detail-img">
        <div className="container mx-auto">
          <div className="flex items-center max-sm:block max-md:block max-xl:block">
            <div className="w-1/2 max-sm:w-full max-md:w-full max-xl:w-full">
              <div className="featured-dishes product-detail-img">
                <div className="sale">
                  <h6>Sale</h6>
                </div>
                <div className="featured-dishes-img">
                  <Image
                    src="/img/product-detail-1.png"
                    width={362}
                    height={453}
                    alt="featured-dishes"
                  />{" "}
                </div>
              </div>
            </div>
            <div className="w-1/2 font-bold font-fredoka max-sm:w-full max-md:w-full max-xl:w-full">
              <div className="available">
                <span className="flex items-center">
                  <FaCheck className="mr-2" />
                  available
                </span>
                <ul className="star">
                  <FaStar />
                  <FaStar />
                  <FaStar />
                  <FaStar />
                  <FaStar />
                </ul>
                <h6>( 1 Review )</h6>
              </div>
              <div className="product-info ">
                <h3 className="text-6xl max-sm:text-3xl">
                  Fried Potatoes With Garlic Chilli Sauce
                </h3>
                <form className="variations_form">
                  <div className="deal-week mb-4 flex items-center">
                    <h2 className="m-0 text-4xl">
                      <span className="text-pink">$</span>10.85
                    </h2>
                    <del className="text-[#555555] text-2xl ml-2">$14.85</del>
                  </div>
                  <h5 className="text-2xl">What’s Included</h5>
                  <p className="text-[#555555]">
                    Sausage, three rashers of streaky bacon, two fried eggs
                  </p>
                  <div className="flex items-center mt-4">
                    <input
                      type="number"
                      className="input-text me-4"
                      step="1"
                      min="1"
                      name="quantity"
                      value="1"
                    />
                    <button className="button bg-pink ml-4">Add to Cart</button>
                  </div>
                  <ul className="product_meta">
                    <li>
                      <span className="theme-bg-clr text-pink">Tags:</span>
                      <ul className="pd-tag">
                        <li>
                          <a href="#" className="ps-0">
                            featured products
                          </a>
                          ,<a href="#">meat</a>,<a href="#">new products</a>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="about-chef font-fredoka">
        <div className="container mx-auto">
          <h2 className="pb-3 font-bold text-5xl">Description</h2>
          <p className="text-[#555555]">
            Nisl quam nestibulum ac quam nec odio elementu sceisu aucan ligula.
            Orci varius natoque pena tibus et magnis dis urient monte ulus mus
            nellent esque habitanum ac quam nec odio rbine. Nisl quam nestibulum
            ac quam nec odio elementu sceisu aucan ligula. toque pena tibus et
            magnis dis u rient monte nascete ridic ulus mus nellentesque
            habitanum ac quam nec odio rbine. Nisl quamu quam nec odio elementu
            sceisu aucan ligula. Orc i varius natoque pena tibus et magnis dis
            urient monte nascete ridic ulus mus a habitanum ac quam nec odio
            rbine. Nisl quam nestibulum ac qua m nec odio elementu sceisu aucan
            ligula. Orci varius natoque pe magnis dis urient monte nascete
            ridiculus mus nellentesque habitanum ac quam nec odio rbine. Nisl
            quam nestibulum ac quam ntoque pena tibus et magnis dis urient monte
            nascete ridic ulus mus nellentesque habitanum ac quam nec odio
            rbine. Nisl quam a quam nec odio elementu sceisu aucan ligula. Orci
            varius natoque pena tibus et magnis dis urient monte nascet e ridic
            ulus mus n habitanum ac quam nec odio rbine.
            <br />
            <br />
            Nisl quam nestibulum ac quam nec odio elementu sceisu aucan ligula.
            Orci varius natoque pena tibus et magnis dis urient monte quam nec
            odio e lementu sceisu aucan ligula. Orci varius natoque pena tibus
            et magnis dis urient monte nascete ridic.
          </p>
        </div>
      </div>
      <Review />
      <Footer />
    </>
  );
};

export default ProductDetails;
