import Head from "next/head";
import React, { useState } from "react";
import { FaHome, FaStar, FaCheck } from "react-icons/fa";
import Image from "next/image";
import Review from "../components/review";
import { addProduct } from "../redux/cartSlice";
import { useDispatch, useSelector } from "react-redux";

const ProductDetails = () => {
  const [quantity, setQuantity] = useState();
  const cart = useSelector((state) => state.cart);
  const dispatch = useDispatch();

  const [foodItem, setFoodItem] = useState({
    id: 1,
    image: "/img/product-detail-1.png",
    name: "Fried Potatoes With Garlic Chilli Sauce",
    price: 10,
    setPrice: 10,
    include: "Sausage, three rashers of streaky bacon, two fried eggs",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda fugit corporis ex laboriosam tenetur at ad aspernatur"
  });

  const setPriceFunction = (value) => {
    setQuantity(value);
    setFoodItem(() => ({
      setPrice: (value * foodItem.price),
      price: 10,
      id: 1,
      image: "/img/product-detail-1.png",
      name: "Fried Potatoes With Garlic Chilli Sauce",
      include: "Sausage, three rashers of streaky bacon, two fried eggs",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda fugit corporis ex laboriosam tenetur at ad aspernatur"
    }));
    if (!value) {
      setFoodItem(() => ({
        price: 10,
        setPrice: 10,
        id: 1,
        image: "/img/product-detail-1.png",
        name: "Fried Potatoes With Garlic Chilli Sauce",
        include: "Sausage, three rashers of streaky bacon, two fried eggs",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda fugit corporis ex laboriosam tenetur at ad aspernatur"
      }));
    }
  }
  const handleClick = () => {
    dispatch(addProduct({ ...foodItem, quantity }));
  };
  console.log(cart);
  return (
    <>
      <Head>
        <title>Product Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
      </Head>
      <div
        className="banner pt-10 pb-10"
        style={{
          backgroundImage: "url(/img/background.png)",
        }}
      >
        <div className="container mx-auto">
          <div className="flex items-center">
            <div className="w-full">
              <div className="title-area-data">
                <h2 className="font-fredoka font-bold text-6xl">
                  Product Detail
                </h2>
                <p>A magical combination that sent aromas to the taste buds</p>
              </div>
              <ol className="breadcrumb bg-pink font-fredoka">
                <li className="breadcrumb-item">
                  <a href="" className="flex items-center">
                    <FaHome /> <span className="ml-3">Home</span>
                  </a>
                </li>
                <li className="breadcrumb-item text-white" aria-current="page">
                  Shop
                </li>
                <li className="breadcrumb-item active" aria-current="page">
                  Product Details
                </li>
              </ol>
            </div>
          </div>
        </div>
      </div>
      <section className="gap featured-dishes-product-detail-img">
        <div className="container mx-auto">
          <div className="flex items-center max-sm:block max-md:block max-xl:block">
            <div className="w-1/2 max-sm:w-full max-md:w-full max-xl:w-full">
              <div className="featured-dishes product-detail-img">
                <div className="sale">
                  <h6>Sale</h6>
                </div>
                <div className="featured-dishes-img">
                  <Image
                    src={foodItem.image}
                    width={362}
                    height={453}
                    alt="featured-dishes"
                  />{" "}
                </div>
              </div>
            </div>
            <div className="w-1/2 font-bold font-fredoka max-sm:w-full max-md:w-full max-xl:w-full">
              <div className="available">
                <span className="flex items-center">
                  <FaCheck className="mr-2" />
                  available
                </span>
                <ul className="star">
                  <FaStar />
                  <FaStar />
                  <FaStar />
                  <FaStar />
                  <FaStar />
                </ul>
                <h6>( 1 Review )</h6>
              </div>
              <div className="product-info ">
                <h3 className="text-6xl max-sm:text-3xl">
                  {foodItem.name}
                </h3>
                <form className="variations_form">
                  <div className="deal-week mb-4 flex items-center">
                    <h2 className="m-0 text-4xl">
                      <span className="text-pink">$</span>{foodItem.setPrice}
                    </h2>
                    <del className="text-[#555555] text-2xl ml-2">$14.85</del>
                  </div>
                  <h5 className="text-2xl">What’s Included</h5>
                  <p className="text-[#555555]">
                    {foodItem.include}
                  </p>
                  <div className="flex items-center mt-4">
                    <input
                      type="number"
                      className="input-text me-4"
                      name="quantity"
                      placeholder="1"
                      onChange={e => { setPriceFunction(parseInt(e.currentTarget.value)); }}
                    />
                    <button className="button bg-pink ml-4" type="button" onClick={handleClick}>Add to Cart</button>
                  </div>
                  <ul className="product_meta">
                    <li>
                      <span className="theme-bg-clr text-pink">Tags:</span>
                      <ul className="pd-tag">
                        <li>
                          <a href="#" className="ps-0">
                            featured products
                          </a>
                          ,<a href="#">meat</a>,<a href="#">new products</a>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="about-chef font-fredoka">
        <div className="container mx-auto">
          <h2 className="pb-3 font-bold text-5xl">Description</h2>
          <p className="text-[#555555]">
            {foodItem.desc}
          </p>
        </div>
      </div>
      <Review />

    </>
  );
};
export default ProductDetails;
