import Head from "next/head";
import React from "react";
import Footer from "../components/layouts/footer";
import Header from "../components/layouts/header";
import Image from "next/image";
import { FaHome, FaStar } from "react-icons/fa";
import Paginate from "../components/paginate";

const ShopItem = () => {
  return (
    <div className="w-1/3 max-md:w-1/2 max-sm:w-full max-lg:w-1/2">
      <div className="featured-dishes">
        <div className="featured-dishes-img">
          <Image
            src="/img/featured-dishes-3.png"
            width={323}
            height={322}
            alt="featured-dishes"
          />
        </div>
        <ul className="star">
          <li>
            <FaStar className="star" />
          </li>
          <li>
            <FaStar className="star" />
          </li>
          <li>
            <FaStar className="star" />
          </li>
          <li>
            <FaStar className="star" />
          </li>
          <li>
            <FaStar className="star" />
          </li>
        </ul>
        <a href="productDetail">
          <h5 className="font-fredoka font-bold text-xl text-black">
            Parisian Hamburger
          </h5>
        </a>
        <p className="font-fredoka font-bold">
          <span className="text-pink">$</span>10.85
        </p>
        <a href="productDetail">
          <i>
            <svg
              className="featured-shopping-bag hover:bg-pink"
              viewBox="0 0 512 512"
              xmlns="http://www.w3.org/2000/svg"
            >
              <g>
                <path d="m452 120h-60.946c-7.945-67.478-65.477-120-135.054-120s-127.109 52.522-135.054 120h-60.946c-11.046 0-20 8.954-20 20v352c0 11.046 8.954 20 20 20h392c11.046 0 20-8.954 20-20v-352c0-11.046-8.954-20-20-20zm-196-80c47.484 0 87.019 34.655 94.659 80h-189.318c7.64-45.345 47.175-80 94.659-80zm176 432h-352v-312h40v60c0 11.046 8.954 20 20 20s20-8.954 20-20v-60h192v60c0 11.046 8.954 20 20 20s20-8.954 20-20v-60h40z"></path>
              </g>
            </svg>
          </i>
        </a>
      </div>
    </div>
  );
};
const Shop = () => {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
      </Head>
      <Header />
      <div
        className="banner pt-10 pb-10"
        style={{
          backgroundImage: "url(/img/background.png)",
        }}
      >
        <div className="container mx-auto">
          <div className="flex items-center">
            <div className="w-full">
              <div className="title-area-data">
                <h2 className="font-fredoka font-bold text-6xl">Shop</h2>
                <p>A magical combination that sent aromas to the taste buds</p>
              </div>
              <ol className="breadcrumb bg-pink font-fredoka">
                <li className="breadcrumb-item">
                  <a href="" className="flex items-center">
                    <FaHome /> <span className="ml-3">Home</span>
                  </a>
                </li>
                <li className="breadcrumb-item active" aria-current="page">
                  Shop
                </li>
              </ol>
            </div>
          </div>
        </div>
      </div>
      <section className="gap">
        <div className="container mx-auto">
          <div className="flex flex-wrap">
            <ShopItem />
            <ShopItem />
            <ShopItem />
            <ShopItem />
            <ShopItem />
            <ShopItem />
          </div>
          <Paginate />
        </div>
      </section>
      <Footer />
    </>
  );
};

export default Shop;
